apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 3s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'exporter'
        static_configs:
          - targets: ['exporter-service:3008']

      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: node  # Discover all Kubernetes nodes

        relabel_configs:
          # Replace the default port (10250) with node-exporter port (9100)
          - source_labels: [__address__]
            regex: '(.*):\d+'  # Match any port
            replacement: '${1}:9100'  # Replace with 9100
            target_label: __address__

          # Set instance to ExternalIP of the node
          - source_labels: [__meta_kubernetes_node_address_ExternalIP]
            target_label: instance  # ExternalIP will be used for instance label

          # Add node name as a label (which is helpful for identifying the nodes)
          - source_labels: [__meta_kubernetes_node_name]
            target_label: node  # This adds the node name to the label
