apiVersion: v1
kind: Service
metadata:
  name: exporter-service
  labels:
    app: mqtt-deployment
spec:
  selector:
    app: mqtt-deployment
  ports:
    - protocol: TCP
      port: 3008        # Port exposed by the service
      targetPort: 3008  # Port on the container (exporter)
  type: ClusterIP
