{
 "title": "MQTT Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Servers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. of MQTT clients connected",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (node) (mqtt_connected_clients)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mqtt_connected_clients)\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Load % (last 5 mins)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Free Memory (GiB)",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance) (node_memory_MemTotal_bytes / (1024^3))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (\n  (node_memory_MemTotal_bytes \n    - node_memory_MemFree_bytes \n    - node_memory_Buffers_bytes \n    - node_memory_Cached_bytes)\n  / (1024^3)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (node_memory_MemFree_bytes / (1024^3))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (node_memory_MemAvailable_bytes / (1024^3))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (\n  (node_memory_Buffers_bytes + node_memory_Cached_bytes) / (1024^3)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}