apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-node-scrape
rules:
  - apiGroups: [""]
    resources: ["nodes","nodes/proxy"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["services","endpoints","pods"]
    verbs: ["get","list","watch"]
  - apiGroups: ["extensions","apps"]
    resources: ["replicasets"]
    verbs: ["get","list","watch"]
